name: Build and publish document image

on:
  workflow_dispatch:
  push:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/neuvector/manifests.git
          cd ./manifests/build/docs
          git clone https://github.com/neuvector/docs.git grav

          docker pull neuvector/docs_base:latest

          echo -e "\n*** build docs container ***\n"
          make docs

          echo -e "\n*** publish docs container ***\n"
          docker login -u nvbuild -p "${{ secrets.DOCKERHUB_NVBUILD_PASSWORD }}"
          docker tag neuvector/docs:latest neuvector/open_docs:latest
          docker push neuvector/open_docs:latest
          docker logout

